//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace napkin.systems.gadgeteer.cerb3 {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The UsbClientSP module using socket 8 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.UsbClientSP usbClientSP;
        
        /// <summary>The LightSensor module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LightSensor lightSensor;
        
        /// <summary>The Barometer module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.Seeed.Barometer barometer;
        
        /// <summary>The LED7C module using socket 5 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7c;
        
        /// <summary>The Char_Display module using socket 7 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Display_HD44780 char_Display;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZCerberus Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZCerberus)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZCerberus();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.usbClientSP = new GTM.GHIElectronics.UsbClientSP(8);
            this.lightSensor = new GTM.GHIElectronics.LightSensor(3);
            this.barometer = new GTM.Seeed.Barometer(2);
            this.led7c = new GTM.GHIElectronics.LED7C(5);
            this.char_Display = new GTM.GHIElectronics.Display_HD44780(7);
        }
    }
}
